# Set the ratio of the current transformer clamps (written on the clamp)
#   For basic hardware this is the current in that produces 1V out. 
#   For intermediate and advanced hardware this is the current in that produces 5A out. 
calculation.current_clamp.config.nominal_current = 50     # Amps

# Select the config file (by removing the leading #) appropriate for your hardware and wiring setup
#module_config_file = "./config/pm_b_1p.toml"             # Basic single phase
#module_config_file = "./config/pm_b_3pb.toml"            # Basic three phase balanced (single clamp)
#module_config_file = "./config/pm_b_3pu.toml"            # Basic three phase unbalanced (3 clamps)
module_config_file = "./config/pm_i_1p.toml"             # Intermediate single phase
#module_config_file = "./config/pm_i_3p.toml"             # Intermediate three phase
#module_config_file = "./config/pm_a_1p.toml"             # Advanced (inc. voltage monitoring) single phase
#module_config_file = "./config/pm_a_3p.toml"             # Advanced (inc. voltage monitoring) three phase
#module_config_file = "./config/pm_b_3pu_mock.toml"       # Basic three phase unbalanced simulator

# If using Basic hardware, set which adc you are using and which channels the clamps are plugged into
# If using Intermediate or Advanced hardware, comment all these out with a #
# adc = oneliner                                          # wip, eg BCRobotics or Grove etc.
# device.adc_0.config.adc_channel = 0
# device.adc_1.config.adc_channel = 1                     # If using multiple clamps
# device.adc_2.config.adc_channel = 2                     # If using multiple clamps
