version: "2"

services:
    timeseries-db:
        extends:
            file: timeseries_datastorage/app.yml
            service: db
        networks:
            internal:
                aliases:
                    - timeseries-db.docker.local
        logging:
            driver: syslog
            options:
                syslog-address: "tcp://localhost:6514"
                syslog-format: "rfc5424"
                tag: timeseries-db
        restart: unless-stopped
        depends_on:
            - "mqtt_broker"
    timeseries-db-input:
        extends:
            file: timeseries_datastorage/app.yml
            service: telegraf
        networks:
            internal:
                aliases:
                    - timeseries-input.docker.local
        logging:
            driver: syslog
            options:
                syslog-address: "tcp://localhost:6514"
                syslog-format: "rfc5424"
                tag: timeseries-db-input
        restart: unless-stopped
        depends_on:
            - "timeseries-db"
            - "mqtt_broker"
    dashboard:
        extends:
            file: dashboards/app.yml
            service: app
        networks:
            internal:
                aliases:
                    - dashboards.docker.local
        logging:
            driver: syslog
            options:
                syslog-address: "tcp://localhost:6514"
                syslog-format: "rfc5424"
                tag: power-monitoring-dashboard
        restart: unless-stopped
        depends_on:
            - "mqtt_broker"
 
   
    current-sensing:
        extends:
            file: current_sensing/app.yml
            service: app
        networks:
            internal:
                aliases:
                    - current-sensing.docker.local
        logging:
            driver: syslog
            options:
                syslog-address: "tcp://localhost:6514"
                syslog-format: "rfc5424"
                tag: current-sensing
        restart: unless-stopped
        depends_on:
            - "mqtt_broker"
 
    graph:
        extends: 
            file: graph/app.yml
            service: app
        networks:
            internal:
                aliases:
                    - graph.docker.local
        logging:
            driver: syslog
            options:
                syslog-address: "tcp://localhost:6514"
                syslog-format: "rfc5424"
                tag: power-monitoring-graph
        restart: unless-stopped
        depends_on: 
            - "timeseries-db"

    analysis:
        extends:
            file: analysis/app.yml
            service: app
        networks:
            internal:
                aliases:
                    - analysis.docker.local
        logging:
            driver: syslog
            options:
                syslog-address: "tcp://localhost:6514"
                syslog-format: "rfc5424"
                tag: power-monitoring-analysis
        restart: unless-stopped       
        depends_on: 
            - "timeseries-db"

 
    mqtt_broker:
        extends:
            file: mqtt_broker/app.yml
            service: app
        restart: unless-stopped
        logging:
            driver: syslog
            options:
                syslog-address: "tcp://localhost:6514"
                syslog-format: "rfc5424"
                tag: mqtt-broker
        networks:
            internal:
                aliases:
                    - mqtt.docker.local
        depends_on: 
            - "alloy"

    alloy:
        image: grafana/alloy:v1.2.0
        command: run --server.http.listen-addr=0.0.0.0:12345 /etc/alloy/config.alloy
        volumes:
        - ./logging/config.alloy:/etc/alloy/config.alloy:ro
        ports:
        - 12345:12345
        - "6514:6514"
        networks:
            internal:
                aliases:
                    - alloy.docker.local

    loki:
        image: grafana/loki:3.1.0
        user: $CURRENT_UID
        ports:
        - "3100:3100"
        command: -config.file=/etc/loki/config.yml
        volumes:
          - ./logging/data:/data
          - ./logging/loki_config.yml:/etc/loki/config.yml
        networks:
            internal:
                aliases:
                    - loki.docker.local

networks:
     internal:
         name: shoestring-internal
