version: "2"

services:
    timeseries-db:
        extends:
            file: timeseries_datastorage/app.yml
            service: db
        networks:
            internal:
                aliases:
                    - timeseries-db.docker.local
        logging:
            driver: syslog
            options:
                tag: docker-timeseries-db
        restart: unless-stopped
        depends_on:
            - "mqtt_broker"
    timeseries-db-input:
        extends:
            file: timeseries_datastorage/app.yml
            service: telegraf
        networks:
            internal:
                aliases:
                    - timeseries-input.docker.local
        logging:
            driver: syslog
            options:
                tag: docker-timeseries-input
        restart: unless-stopped
        depends_on:
            - "timeseries-db"
            - "mqtt_broker"
    dashboard:
        extends:
            file: dashboards/app.yml
            service: app
        networks:
            internal:
                aliases:
                    - dashboards.docker.local
        logging:
            driver: syslog
            options:
                tag: docker-dashboards
        restart: unless-stopped
        depends_on:
            - "mqtt_broker"
 
   
    current-sensing:
        extends:
            file: current_sensing/app.yml
            service: app
        networks:
            internal:
                aliases:
                    - current-sensing.docker.local
        logging:
            driver: syslog
            options:
                tag: docker-current-sensing
        restart: unless-stopped
        depends_on:
            - "mqtt_broker"
 
    graph:
        extends: 
            file: graph/app.yml
            service: app
        networks:
            internal:
                aliases:
                    - graph.docker.local
        logging:
            driver: syslog
            options:
                tag: docker-graph
        restart: unless-stopped

    analysis:
        extends:
            file: analysis/app.yml
            service: app
        networks:
            internal:
                aliases:
                    - analysis.docker.local
        logging:
            driver: syslog
            options:
                tag: docker-analysis
        restart: unless-stopped       

 
    mqtt_broker:
        extends:
            file: mqtt_broker/app.yml
            service: app
        restart: unless-stopped
        logging:
            driver: syslog
            options:
                tag: docker-mqtt-broker
        networks:
            internal:
                aliases:
                    - mqtt.docker.local

networks:
     internal:
         name: shoestring-internal
