auth_enabled: false

server:
  http_listen_port: 3100
  grpc_server_max_recv_msg_size: 268435456 #256 MB
  grpc_server_max_send_msg_size: 268435456 #256 MB


schema_config:
  configs:
    # New TSDB schema
    - index:
        period: 24h
        prefix: index_
      object_store: filesystem
      schema: v13
      store: tsdb

storage_config:
  tsdb_shipper:
    active_index_directory: /data/tsdb-index
    cache_location: /data/tsdb-cache

common:
  path_prefix: /data
  storage:
    filesystem:
      chunks_directory: /data/chunks
      rules_directory: /data/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_scheduler:
  # the TSDB index dispatches many more, but each individually smaller, requests. 
  # We increase the pending request queue sizes to compensate.
  max_outstanding_requests_per_tenant: 32768

querier:
  max_concurrent: 4



compactor:
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 10
  delete_request_store: filesystem

# documentation: https://grafana.com/docs/loki/latest/operations/storage/retention/
limits_config:
  max_entries_limit_per_query: 100000 # increase query entry limits
  retention_period: 168h # 7 days for all logs
  retention_stream:
  - selector: '{level="debug"}' # 1 day for logs with debug level
    priority: 1
    period: 24h # must be >=24h

analytics:
  reporting_enabled: false