version: "2"

services:
    app:
        build: .
        command: ["python","main.py","--log","info"]
        privileged: true
        volumes:
            - ./config:/app/config
        environment:
            - MODULE_CONFIG_FILE=/app/config/pm_b_3pu_mock.toml
