{
 "title": "Historic (All)",
 "tags": [ "power_monitoring" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "const_bucket", "label": "Influx Bucket", "query": "power_monitoring" },
   {
    "name": "bucket",
    "label": "Time Bucket",
    "query": "1m,10m,30m,1h,6h,8h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Current History",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "limited_window = if int(v: v.windowPeriod) > int(v: 5s) then v.windowPeriod else 5s\r\n\r\nfrom(bucket: \"${const_bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"equipment_power_usage\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current\")\r\n  |> aggregateWindow(every: limited_window, fn: mean, createEmpty: true)\r\n  |> pivot(columnKey: [\"_field\"], rowKey: [\"_time\"], valueColumn: \"_value\")\r\n  |> group(columns: [\"machine\",\"_time\"])\r\n  |> sum(column: \"current\")\r\n  |> group(columns: [\"machine\"])\r\n  |> keep(columns: [\"current\",\"_time\",\"machine\"])"
    }
   ]
  },
  {
   "title": "Total Energy Usage in Timeframe",
   "type": "stat",
   "gridPos": { "h": 20, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "limited_window = if int(v: v.windowPeriod) > int(v: 5s) then v.windowPeriod else 5s\r\n\r\nfrom(bucket: \"${const_bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"energy\")\r\n  |> group(columns:[\"machine\",\"_field\"])\r\n  |> sum()\r\n  |> keep(columns: [\"_value\",\"machine\"])"
    }
   ]
  },
  {
   "title": "Total Power History",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "limited_window = if int(v: v.windowPeriod) > int(v: 5s) then v.windowPeriod else 5s\r\n\r\nfrom(bucket: \"${const_bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"equipment_power_usage\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"power_real\")\r\n  |> aggregateWindow(every: limited_window, fn: mean, createEmpty: true)\r\n  |> pivot(columnKey: [\"_field\"], rowKey: [\"_time\"], valueColumn: \"_value\")\r\n  |> keep(columns: [\"power_real\",\"_time\",\"machine\"])"
    }
   ]
  },
  {
   "title": " Total Energy History",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "limited_window = if int(v: v.windowPeriod) > int(v: 5s) then v.windowPeriod else 5s\r\n\r\nfrom(bucket: \"${const_bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"energy\")\r\n  |> aggregateWindow(every: ${bucket}, fn: mean, createEmpty: true)\r\n  |> pivot(columnKey: [\"_field\"], rowKey: [\"_time\"], valueColumn: \"_value\")\r\n  |> keep(columns: [\"energy\",\"_time\",\"phase\",\"machine\"])"
    }
   ]
  }
 ]
}