services:
    graph:
        build: .

        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./config/ui:/usr/share/nginx/html/config/

        ports:
            - "8080:80"

        networks:
            internal:
                aliases:
                    - graph.docker.local

        logging:
            driver: syslog
            options:
                tag: docker-graph

        restart: unless-stopped