#[config]
#	default_voltage=230
 [config.voltage_line_neutral]
	default = 230
[config.influx]
	url = "http://timeseries-db.docker.local:8086"
	token = "<Should be overwritten by environment variable>"
	org = "SHOESTRING"
[config.power_factor]
	default = 1.0
	

[routes.real_power]
	path="/power/real"
	methods=["get"]
	module="electical"
	function="real_power"
	[routes.real_power.config]


[routes.apparent_power]
	path="/power/apparent"
	methods=["get"]
	module="electical"
	function="apparent_power"
	[routes.apparent_power.config]

[routes.energy_bucket]
	path="/energy/bucket"
	methods=["get"]
	module="electical"
	function="energy_bucket"
	[routes.energy_bucket.config]

[routes.energy_total]
	path="/energy/total"
	methods=["get"]
	module="electical"
	function="energy_total"
	[routes.energy_total.config]
	
[routes.period]
	path="/period"
	methods=["get"]
	module="electical"
	function="period_comparison"
	[routes.period.config]

[routes.top10]
	path="/period/top10"
	methods=["get"]
	module="electical"
	function="top_10"
	[routes.top10.config]
