version: '2'

services:
  app:
    build: .
    command: ["python","main.py","--log","info"]
    environment:
      - CONFIG__INFLUX__TOKEN=${DB_ADMIN_INITIAL_TOKEN}
    ports:
      - '8000:80'
    volumes:
      - ./config:/app/config:ro
