version: '2'

services:
  app:
    build: .
    command: ["python","main.py","--log","info"]
    environment:
      - INFLUX__TOKEN=${DB_ADMIN_INITIAL_TOKEN}
    ports:
      - '80:80'
    volumes:
      - ./config:/app/config:ro
      - ./data:/app/data
