#=-= Define Interface Modules =-=
[interface.mb1]
    module="modbus"
    class="ModbusTCPSync"
[interface.mb1.config]
    adapter_addr="192.168.0.7"
    adapter_port=502

#=-= Define Device Modules =-=
[device.mfm1]
    module="multi_function_meter_HOBUT"
    class="HOBUT_850_LTHN"
    interface="mb1"
[device.mfm1.config]
    slave_id=1
[device.mfm1.variables]
    I1 = "current_rms_A"
    I2 = "current_rms_B"
    I3 = "current_rms_C"

#=-= Define Calculation Modules =-=
[calculation]

#=-= Define Calculation Pipelines =-=
[pipelines]
    empty_pipeline = []

#=-= Define Measurements Pipelines =-=
[measurement]
    module="gen_sample"
    class="SingleSample"
[measurement.config]
    period = 1.0 # seconds
[[measurement.sensing_stacks]]
    device = "mfm1"
    pipeline = "empty_pipeline"
    
[output.phase_a]
    path = "power_monitoring/{{machine}}/{{phase}}"
[output.phase_a.spec]
    machine = "#Lab_Int_3PU"
    timestamp = '$.timestamp'
    current = "$.current_rms_A"
    phase = "#A"
 
[output.phase_b]
    path = "power_monitoring/{{machine}}/{{phase}}"
[output.phase_b.spec]
    machine = "#Lab_Int_3PU"
    timestamp = '$.timestamp'
    current = "$.current_rms_B"
    phase = "#B"
 
[output.phase_c]
    path = "power_monitoring/{{machine}}/{{phase}}"
[output.phase_c.spec]
    machine = "#Lab_Int_3PU"
    timestamp = '$.timestamp'
    current = "$.current_rms_C"
    phase = "#C"

[mqtt]
    broker = "mqtt.docker.local"
    port = 1883   #common mqtt ports are 1883 and 8883
    base_topic_template = ""

    #reconnection characteristics
    # start: timeout = initial,
    # if timeout < limit then
    #   timeout = timeout*backoff
    # else
    #   timeout = limit
    reconnect.initial = 5 # seconds
    reconnect.backoff = 2 # multiplier
    reconnect.limit = 60 # seconds
