name: Use issue to tracker workflow

on:
  issues:
    types:
      - opened
      - reopened

jobs:
  call-issue-to-tracker:
    uses: DigitalShoestringSolutions/CommonWorkflows/.github/workflows/add_issues_to_tracker.yml
